In [7]:
from src.data_loader import load_data, validate_data,preprocess_data, get_summary_stats, get_segment_analysis, get_quarterly_trends, get_rep_performance, create_heatmap_data

In [3]:
df = load_data()
df.head()

,deal_id,created_date,closed_date,sales_rep_id,industry,region,product_type,lead_source,deal_stage,deal_amount,sales_cycle_days,outcome
0,D00001,2023-11-24,2023-12-15,rep_22,SaaS,North America,Enterprise,Referral,Qualified,4253,21,Won
1,D00002,2023-01-17,2023-01-27,rep_7,SaaS,India,Core,Referral,Closed,3905,10,Won
2,D00003,2023-10-29,2023-12-10,rep_5,HealthTech,APAC,Core,Inbound,Proposal,10615,42,Lost
3,D00004,2023-07-14,2023-08-02,rep_18,FinTech,India,Core,Partner,Negotiation,4817,19,Won
4,D00005,2024-02-29,2024-05-26,rep_2,HealthTech,APAC,Core,Outbound,Qualified,45203,87,Lost

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   deal_id           5000 non-null   object
 1   created_date      5000 non-null   object
 2   closed_date       5000 non-null   object
 3   sales_rep_id      5000 non-null   object
 4   industry          5000 non-null   object
 5   region            5000 non-null   object
 6   product_type      5000 non-null   object
 7   lead_source       5000 non-null   object
 8   deal_stage        5000 non-null   object
 9   deal_amount       5000 non-null   int64
 10  sales_cycle_days  5000 non-null   int64
 11  outcome           5000 non-null   object
dtypes: int64(2), object(10)
memory usage: 468.9+ KB

In [4]:
validate_data(df)

{'total_rows': 5000,
 'total_columns': 12,
 'missing_values': {'deal_id': 0,
  'created_date': 0,
  'closed_date': 0,
  'sales_rep_id': 0,
  'industry': 0,
  'region': 0,
  'product_type': 0,
  'lead_source': 0,
  'deal_stage': 0,
  'deal_amount': 0,
  'sales_cycle_days': 0,
  'outcome': 0},
 'duplicates': np.int64(0),
 'date_range': {'created_min': '2023-01-01',
  'created_max': '2024-03-26',
  'closed_min': '2023-01-11',
  'closed_max': '2024-07-20'},
 'unique_values': {'industries': 5,
  'regions': 4,
  'product_types': 3,
  'lead_sources': 4,
  'sales_reps': 25,
  'deal_stages': 5},
 'outcome_distribution': {'Lost': 2737, 'Won': 2263},
 'is_valid': True}

In [12]:
prep = preprocess_data(df)
prep.head()

,deal_id,created_date,closed_date,sales_rep_id,industry,region,product_type,lead_source,deal_stage,deal_amount,...,created_month,created_quarter,created_year_quarter,closed_year,closed_month,closed_quarter,closed_year_quarter,is_won,deal_size_category,cycle_category
0,D00001,2023-11-24,2023-12-15,rep_22,SaaS,North America,Enterprise,Referral,Qualified,4253,...,11,4,2023Q4,2023,12,4,2023Q4,1,Small (<$10K),Fast (<30d)
1,D00002,2023-01-17,2023-01-27,rep_7,SaaS,India,Core,Referral,Closed,3905,...,1,1,2023Q1,2023,1,1,2023Q1,1,Small (<$10K),Fast (<30d)
2,D00003,2023-10-29,2023-12-10,rep_5,HealthTech,APAC,Core,Inbound,Proposal,10615,...,10,4,2023Q4,2023,12,4,2023Q4,0,Medium ($10K-$25K),Normal (30-60d)
3,D00004,2023-07-14,2023-08-02,rep_18,FinTech,India,Core,Partner,Negotiation,4817,...,7,3,2023Q3,2023,8,3,2023Q3,1,Small (<$10K),Fast (<30d)
4,D00005,2024-02-29,2024-05-26,rep_2,HealthTech,APAC,Core,Outbound,Qualified,45203,...,2,1,2024Q1,2024,5,2,2024Q2,0,Large ($25K-$50K),Slow (60-90d)

In [11]:
get_summary_stats(prep)

{'total_deals': 5000,
 'won_deals': np.int64(2263),
 'lost_deals': np.int64(2737),
 'overall_win_rate': np.float64(45.26),
 'total_revenue_won': np.int64(60589278),
 'total_revenue_lost': np.int64(70843186),
 'avg_deal_size': np.float64(26286.4928),
 'avg_deal_size_won': np.float64(26773.874502872295),
 'avg_deal_size_lost': np.float64(25883.516989404456),
 'avg_sales_cycle': np.float64(63.7518),
 'avg_sales_cycle_won': np.float64(63.17322138753867),
 'avg_sales_cycle_lost': np.float64(64.230179028133),
 'median_deal_size': np.float64(14171.5),
 'median_sales_cycle': np.float64(64.0)}

In [14]:
get_quarterly_trends(prep)

,closed_year_quarter,total_deals,won_deals,total_revenue,avg_deal_size,avg_cycle_days,win_rate,revenue_won,win_rate_change,revenue_change_pct
0,2023Q1,328,146,7689967,23445.021341,35.795732,44.51,3565155,NaN,NaN
1,2023Q2,973,438,24880389,25570.800617,61.382323,45.02,10990875,0.51,208.286035
2,2023Q3,1016,435,27899635,27460.270669,64.538386,42.81,12822748,-2.21,16.667217
3,2023Q4,1027,488,26799813,26095.241480,62.713729,47.52,12714626,4.71,-0.843205
4,2024Q1,990,462,26413879,26680.685859,63.139394,46.67,12702445,-0.85,-0.095803
5,2024Q2,637,279,17009398,26702.351648,80.921507,43.80,7518918,-2.87,-40.807317
6,2024Q3,29,15,739383,25495.965517,112.413793,51.72,274511,7.92,-96.349062